//const String ROOT="http://192.168.0.13"; //ip of my local machine, in my house1
//const String ROOT="http://192.168.0.23"; //ip of my local machine, in my house3
//const String ROOT="http://192.168.0.4"; //ip of my local machine, in my house2
//const String ROOT="http://192.168.1.54"; //ip of my local machine at work
//const String ROOT="http://maindsteel.tech"; //ip of maindsteel.tech
const String ROOT="https://up-panammun.herokuapp.com";
//const String ROOT = "https://panammun-production.up.railway.app";
/*const String REGISTRATION="$ROOT/api/registration.php";
const String LOGIN="$ROOT/api/login.php";
const String COMITES="$ROOT/api/comites.php";
const String PAISES = "$ROOT/api/paises.php";
const String PAISESVOTACION = "$ROOT/api/paisesvotacion.php";
const String ESCUELAS = "$ROOT/api/escuelas.php";
const String NOMINACIONES = "$ROOT/api/nominaciones.php";
const String VOTACIONES = "$ROOT/api/votaciones.php";
const String PDFURL = "$ROOT/api/test_upload.php";
const String PDFURL2 = "$ROOT/api/test_upload2.php";
const String alumnipage = "$ROOT/api/alumni.php";
const String RECHARGE = "$ROOT/api/recarga.php";*/
const String REGISTRATION="$ROOT/registration.php";
const String LOGIN="$ROOT/login.php";
const String COMITES="$ROOT/comites.php";
const String PAISES = "$ROOT/paises.php";
const String PAISESVOTACION = "$ROOT/paisesvotacion.php";
const String ESCUELAS = "$ROOT/escuelas.php";
const String NOMINACIONES = "$ROOT/nominaciones.php";
const String VOTACIONES = "$ROOT/votaciones.php";
const String PDFURL = "$ROOT/test_upload.php";
const String PDFURL2 = "$ROOT/test_upload2.php";
const String alumnipage = "$ROOT/alumni.php";
const String RECHARGE = "$ROOT/recarga.php";
const String DELETEUSER = "$ROOT/deleteuser.php";